// <auto-generated />
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Security.Cryptography;
using Microsoft.EntityFrameworkCore.XuGu.Infrastructure.Internal;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using XuguClient;

namespace Microsoft.EntityFrameworkCore.XuGu.ValueGeneration.Internal
{
    public class XGSequentialGuidValueGenerator : ValueGenerator<Guid>
    {
        private readonly IXGOptions _options;

        public XGSequentialGuidValueGenerator(IXGOptions options)
        {
            _options = options;
        }

        private static readonly RandomNumberGenerator _rng = RandomNumberGenerator.Create();

        /// <summary>
        ///     Gets a value to be assigned to a property.
        ///     Creates a GUID where the first 8 bytes are the current UTC date/time (in ticks)
        ///     and the rest are cryptographically random. This allows for better performance
        ///     in clustered index scenarios.
        /// </summary>
        /// <para>The change tracking entry of the entity for which the value is being generated.</para>
        /// <returns> The value to be assigned to a property. </returns>
        public override Guid Next(EntityEntry entry)
        {
            return Next();
        }

        public virtual Guid Next()
        {
            return Next(DateTimeOffset.UtcNow);
        }

        public virtual Guid Next(DateTimeOffset timeNow)
        {
            var guid = new Guid();

            return guid;
        }

        /// <summary>
        ///     Gets a value indicating whether the values generated are temporary or permanent. This implementation
        ///     always returns false, meaning the generated values will be saved to the database.
        /// </summary>
        public override bool GeneratesTemporaryValues => false;
    }
}
