// <auto-generated />
// The .NET Foundation licenses this file to you under the MIT license.

using JetBrains.Annotations;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.XuGu.Infrastructure.Internal;
using Microsoft.EntityFrameworkCore.XuGu.Query.ExpressionTranslators.Internal;
using Microsoft.EntityFrameworkCore.XuGu.Query.ExpressionVisitors.Internal;
using Microsoft.EntityFrameworkCore.XuGu.Storage.Internal;

namespace Microsoft.EntityFrameworkCore.XuGu.Query.Internal
{
    public class XGMethodCallTranslatorProvider : RelationalMethodCallTranslatorProvider
    {
        public XGMethodCallTranslatorProvider(
            [NotNull] RelationalMethodCallTranslatorProviderDependencies dependencies,
            [NotNull] IXGOptions options)
            : base(dependencies)
        {
            var sqlExpressionFactory = (XGSqlExpressionFactory)dependencies.SqlExpressionFactory;
            var relationalTypeMappingSource = (XGTypeMappingSource)dependencies.RelationalTypeMappingSource;

            AddTranslators(new IMethodCallTranslator[]
            {
                new XGByteArrayMethodTranslator(sqlExpressionFactory),
                new XGConvertTranslator(sqlExpressionFactory),
                new XGDateTimeMethodTranslator(sqlExpressionFactory),
                new XGDateDiffFunctionsTranslator(sqlExpressionFactory),
                new XGDbFunctionsExtensionsMethodTranslator(sqlExpressionFactory),
                new XGJsonDbFunctionsTranslator(sqlExpressionFactory),
                new XGMathMethodTranslator(sqlExpressionFactory),
                new XGNewGuidTranslator(sqlExpressionFactory),
                new XGObjectToStringTranslator(sqlExpressionFactory),
                new XGRegexIsMatchTranslator(sqlExpressionFactory),
                new XGStringComparisonMethodTranslator(sqlExpressionFactory, options),
                new XGStringMethodTranslator(sqlExpressionFactory, relationalTypeMappingSource, options),
            });
        }
    }
}
