<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
	  <LangVersion>9.0</LangVersion>
	  <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetTopologySuite" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFCore.XuGu\EFCore.XuGu.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>..\..\..\efcore5\artifacts\bin\EFCore\Debug\netstandard2.1\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Relational">
      <HintPath>..\..\..\efcore5\artifacts\bin\EFCore.Relational\Debug\netstandard2.1\Microsoft.EntityFrameworkCore.Relational.dll</HintPath>
    </Reference>
    <Reference Include="XuguClient">
      <HintPath>..\..\..\csharp-driver\XGCSClient\bin\Debug\netstandard2.1\XuguClient.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\XGNTSStrings.Designer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>XGNTSStrings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\XGNTSStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>XGNTSStrings.Designer.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
