// <auto-generated />

using System;
using System.Linq.Expressions;
using System.Reflection;
using JetBrains.Annotations;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Microsoft.EntityFrameworkCore.XuGu.Infrastructure.Internal;
using Microsoft.EntityFrameworkCore.XuGu.Storage.Internal;
using XuguClient;

namespace Microsoft.EntityFrameworkCore.XuGu.Json.Newtonsoft.Storage.Internal
{
    public class XGJsonNewtonsoftTypeMapping<T> : XGJsonTypeMapping<T>
    {
        // Called via reflection.
        // ReSharper disable once UnusedMember.Global
        public XGJsonNewtonsoftTypeMapping(
            [NotNull] string storeType,
            [CanBeNull] ValueConverter valueConverter,
            [CanBeNull] ValueComparer valueComparer,
            [NotNull] IXGOptions options)
            : base(
                storeType,
                valueConverter,
                valueComparer,
                options)
        {
        }

        protected XGJsonNewtonsoftTypeMapping(
            RelationalTypeMappingParameters parameters,
            XGDbType xgDbType,
            IXGOptions options)
            : base(parameters, xgDbType, options)
        {
        }

        protected override RelationalTypeMapping Clone(RelationalTypeMappingParameters parameters)
            => new XGJsonNewtonsoftTypeMapping<T>(parameters, XGDbType, Options);

        public override Expression GenerateCodeLiteral(object value)
            => value switch
            {
                JToken jToken => Expression.Call(
                    typeof(JToken).GetMethod(nameof(JToken.Parse), new[] {typeof(string), typeof(JsonLoadSettings)}),
                    Expression.Constant(jToken.ToString(Formatting.None)),
                    Expression.New(typeof(JsonLoadSettings))),
                string s => Expression.Constant(s),
                _ => throw new NotSupportedException("Cannot generate code literals for JSON POCOs.")
            };
    }
}
