<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>

    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

	
	<ItemGroup>
		<Compile Include="..\Shared\**\*.cs" />
	</ItemGroup>

	
	<ItemGroup>
	  <Compile Include="..\..\src\Shared\CodeAnnotations.cs" Link="CodeAnnotations.cs" />
	  <Compile Include="..\..\src\Shared\EnumerableExtensions.cs" Link="EnumerableExtensions.cs" />
	  <Compile Include="..\..\src\Shared\ReferenceEqualityComparer.cs" Link="ReferenceEqualityComparer.cs" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational.Specification.Tests" Version="5.0.10" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="5.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="5.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="5.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
	  <PackageReference Include="xunit.assert" Version="2.4.1" />
	  <PackageReference Include="xunit.core" Version="2.4.1" />
	  <PackageReference Include="xunit.runner.console" Version="2.4.1">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EFCore.XuGu.Json.Microsoft\EFCore.XuGu.Json.Microsoft.csproj" />
    <ProjectReference Include="..\..\src\EFCore.XuGu.Json.Newtonsoft\EFCore.XuGu.Json.Newtonsoft.csproj" />
    <ProjectReference Include="..\..\src\EFCore.XuGu.NTS\EFCore.XuGu.NTS.csproj" />
    <ProjectReference Include="..\..\src\EFCore.XuGu\EFCore.XuGu.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>..\..\..\efcore5\artifacts\bin\EFCore\Debug\netstandard2.1\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Design">
      <HintPath>..\..\..\mysql_efcore5\test\EFCore.MySql.FunctionalTests\bin\Debug\net5.0\Microsoft.EntityFrameworkCore.Design.dll</HintPath>
    </Reference>
    <Reference Include="XuguClient">
      <HintPath>..\..\..\csharp-driver\XGCSClient\bin\Debug\netstandard2.1\XuguClient.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config.json.example">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Northwind.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TestModels\" />
  </ItemGroup>

</Project>
