<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>9.0</LangVersion>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	

	<ItemGroup>
		<Compile Include="..\Shared\**\*.cs" />
	</ItemGroup>

	

	<ItemGroup>
	  <None Remove="Properties\XGStrings.Designer.tt" />
	</ItemGroup>

	

	<ItemGroup>
	  <EmbeddedResource Include="Properties\XGStrings.Designer.tt">
	    <Generator>TextTemplatingFileGenerator</Generator>
	    <LastGenOutput>XGStrings.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="5.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.10" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.2" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="5.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="5.0.0" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="XuguClient">
			<HintPath>..\..\..\csharp-driver\XGCSClient\bin\Debug\netstandard2.1\XuguClient.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Update="Properties\XGJsonStrings.Designer.tt">
			<Generator>TextTemplatingFileGenerator</Generator>
			<LastGenOutput>XGJsonStrings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\XGJsonStrings.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>XGJsonStrings.Designer.tt</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>
