//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.EntityFrameworkCore.XuGu {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.EntityFrameworkCore.XuGu.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Identity value generation cannot be used for the property &apos;{property}&apos; on entity type &apos;{entityType}&apos; because the property type is &apos;{propertyType}&apos;. Identity value generation can only be used with signed integer properties. 的本地化字符串。
        /// </summary>
        internal static string IdentityBadType {
            get {
                return ResourceManager.GetString("IdentityBadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value provided for argument &apos;{argumentName}&apos; must be a valid value of enum type &apos;{enumType}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The increment value of &apos;{increment}&apos; for sequence &apos;{sequenceName}&apos; cannot be used for value generation. Sequences used for value generation must have positive increments. 的本地化字符串。
        /// </summary>
        internal static string SequenceBadBlockSize {
            get {
                return ResourceManager.GetString("SequenceBadBlockSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL Server sequences cannot be used to generate values for the property &apos;{property}&apos; on entity type &apos;{entityType}&apos; because the property type is &apos;{propertyType}&apos;. Sequences can only be used with integer properties. 的本地化字符串。
        /// </summary>
        internal static string SequenceBadType {
            get {
                return ResourceManager.GetString("SequenceBadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL Server-specific methods can only be used when the context is using a SQL Server data store. 的本地化字符串。
        /// </summary>
        internal static string SqlServerNotInUse {
            get {
                return ResourceManager.GetString("SqlServerNotInUse", resourceCulture);
            }
        }
    }
}
