// <auto-generated />

using System;
using System.Reflection;
using System.Resources;
using JetBrains.Annotations;

namespace EFCore.XuGu.NTS.Properties
{
    /// <summary>
    ///     <para>
    ///		    String resources used in EF exceptions, etc.
    ///     </para>
    ///     <para>
    ///		    These strings are exposed publicly for use by database providers and extensions.
    ///         It is unusual for application code to need these strings.
    ///     </para>
    /// </summary>
    public static class XGNTSStrings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("EFCore.XuGu.NTS.Properties.XGNTSStrings", typeof(XGNTSStrings).GetTypeInfo().Assembly);

        /// <summary>
        ///     UseNetTopologySuite requires AddEntityFrameworkXuGuNetTopologySuite to be called on the internal service provider used.
        /// </summary>
        public static string NTSServicesMissing
            => GetString("NTSServicesMissing");

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);
            for (var i = 0; i < formatterNames.Length; i++)
            {
                value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
            }

            return value;
        }
    }
}

