// <auto-generated />

using System.Runtime.CompilerServices;
using Microsoft.EntityFrameworkCore.Design;

[assembly: DesignTimeProviderServices("Microsoft.EntityFrameworkCore.XuGu.Design.Internal.XGDesignTimeServices")]
[assembly: InternalsVisibleTo("Microsoft.EntityFrameworkCore.XuGu.FunctionalTests")]
[assembly: InternalsVisibleTo("Microsoft.EntityFrameworkCore.XuGu.Tests")]
