// <auto-generated />

using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Scaffolding;

namespace Microsoft.EntityFrameworkCore.XuGu.Json.Microsoft.Scaffolding.Internal
{
    public class XGJsonMicrosoftCodeGeneratorPlugin : ProviderCodeGeneratorPlugin
    {
        private static readonly MethodInfo _useMicrosoftJsonMethodInfo =
            typeof(XGJsonMicrosoftDbContextOptionsBuilderExtensions).GetRequiredRuntimeMethod(
                nameof(XGJsonMicrosoftDbContextOptionsBuilderExtensions.UseMicrosoftJson),
                typeof(XGDbContextOptionsBuilder),
                typeof(XGCommonJsonChangeTrackingOptions));

        public override MethodCallCodeFragment GenerateProviderOptions()
            => new MethodCallCodeFragment(_useMicrosoftJsonMethodInfo);
    }
}
