// <auto-generated />
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microsoft.EntityFrameworkCore.XuGu.Storage.Internal
{
    public class BytesToDateTimeConverter : ValueConverter<byte[], DateTime>
    {
        private static readonly NumberToBytesConverter<long> _longToBytes
            = new NumberToBytesConverter<long>();

        public BytesToDateTimeConverter()
            : base(
                v => DateTime.FromBinary((long)_longToBytes.ConvertFromProvider(v)),
                v => (byte[])_longToBytes.ConvertToProvider(v.ToBinary()))
        {
        }
    }
}
