// <auto-generated />
// The .NET Foundation licenses this file to you under the MIT license.

using Microsoft.EntityFrameworkCore.Storage;

namespace Microsoft.EntityFrameworkCore.XuGu.Storage.Internal;

public interface IJsonSpecificTypeMapping
{
    RelationalTypeMapping CloneAsJsonCompatible();
}
