// <auto-generated />
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Data.Common;
using System.Linq;
using XuguClient;

namespace Microsoft.EntityFrameworkCore.XuGu.Storage.Internal
{
    public class XGConnectionSettings
    {
        public XGConnectionSettings()
        {
        }

        public XGConnectionSettings(DbConnection connection)
            : this(connection.ConnectionString)
        {
        }

        public XGConnectionSettings(string connectionString)
        {
        }
        public virtual bool? TreatTinyAsBoolean { get; }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            if (obj.GetType() != this.GetType())
            {
                return false;
            }

            return Equals((XGConnectionSettings)obj);
        }

        public override int GetHashCode()
        {
            throw new NotImplementedException();
        }
    }
}
