// <auto-generated />
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using Microsoft.EntityFrameworkCore.Storage;
using XuguClient;
using Microsoft.EntityFrameworkCore.XuGu.Utilities;

namespace Microsoft.EntityFrameworkCore.XuGu.Storage.Internal
{
    public class XGGuidTypeMapping : GuidTypeMapping
    {

        public XGGuidTypeMapping()
            : this(new RelationalTypeMappingParameters(
                    new CoreTypeMappingParameters(typeof(Guid)),
                    "guid",
                    StoreTypePostfix.Size,
                    System.Data.DbType.Guid,
                    false,
                    null,
                    true))
        {
        }

        protected XGGuidTypeMapping(RelationalTypeMappingParameters parameters)
            : base(parameters)
        {
        }

        protected override RelationalTypeMapping Clone(RelationalTypeMappingParameters parameters)
            => new XGGuidTypeMapping(parameters);


        protected override string GenerateNonNullSqlLiteral(object value)
        {
            throw new ArgumentOutOfRangeException();
        }
    }
}
