// <auto-generated />
// The .NET Foundation licenses this file to you under the MIT license.


using JetBrains.Annotations;
using Microsoft.EntityFrameworkCore.Storage;
using XuguClient;

namespace Microsoft.EntityFrameworkCore.XuGu.Storage.Internal
{
    public class XGYearTypeMapping : XGTypeMapping
    {
        public XGYearTypeMapping([NotNull] string storeType)
            : base(
                storeType,
                typeof(short),
                XGDbType.TinyInt,
                System.Data.DbType.Int16)
        {
        }

        protected XGYearTypeMapping(RelationalTypeMappingParameters parameters, XGDbType xgDbType)
            : base(parameters, xgDbType)
        {
        }

        protected override RelationalTypeMapping Clone(RelationalTypeMappingParameters parameters)
            => new XGYearTypeMapping(parameters, XGDbType);
    }
}
